
GOOGLELOGIN_CLIENT_ID: "819351028781-orn7ikm2gbtpj41fr19omroon85m1l6d.apps.googleusercontent.com"
GOOGLELOGIN_CLIENT_SECRET: "qdrzP3VmZau37VxWj2sPnCNQ"
GOOGLELOGIN_SCOPE: "profile email"
GOOGLELOGIN_REDIRECT_URI: "http://localhost:8080/login/oauth2callback"

# change the DB settings if your database settings are different
db_parameters:
    dbn: "postgres"
    db: "voternet"
    #pw: "secret"
    #host: "db-server"

# Specify your state here
state: "KA"

# Title of the website
site_title: "Clean Sweep"

## Optionally you can specify a vounteer signup URL to display on the permission denied page.
# volunteer_signup_url 

# Generate a new random secret key when you are deploying in production.
secret_key: "uzVzOlbbYyjOvGfSawkR"

error_email_recipients:
    - youremail@example.com

from_address: 
    - noreply@example.com

error_from_address: noreply@example.com

search_db: xappy
google_analytics_id: "XXXX"

